### ISSUE TITLE
wow works very nice

### ISSUE THREAD

**Issue by NeverBeLazyG** [Hezkore/bash-ai#1]
![image](https://github.com/user-attachments/assets/559883d8-1971-4aee-b89a-994f0818f134)

thanks for that fail script, and thanks that you wasnt able to test such a mini script before releasing.

**Comment by Hezkore** [comment]
Thanks.
And you're welcome.

**Comment by NeverBeLazyG** [comment]
😂

**Comment by NeverBeLazyG** [comment]
I forked it and added Promt HISTORY functionality like in a CLI. https://github.com/NeverBeLazyG/bash-ai-plus

**Comment by Hezkore** [comment]
Cool.
I guess it actually worked then 🤷‍♂️

**Comment by NeverBeLazyG** [comment]
yeh, it was because of my wsl instance. 😂

**Comment by NeverBeLazyG** [comment]
i made a windows powershell version in powershell. will release it, after testing a while. but it runs 
![image](https://github.com/user-attachments/assets/1369f94b-ef74-4475-aa0d-3ff2ea225c11)
